"""Start Database

Revision ID: 2ce366929ddf
Revises: 
Create Date: 2024-05-27 21:30:44.307746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce366929ddf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('users_id', sa.UUID(), nullable=False),
    sa.Column('users_cod_cpf', sa.String(length=11), nullable=False),
    sa.Column('users_email', sa.String(length=45), nullable=False),
    sa.Column('users_nam', sa.String(length=100), nullable=False),
    sa.Column('users_has_password', sa.String(length=255), nullable=False),
    sa.Column('users_cod_sex', sa.String(length=1), nullable=False),
    sa.Column('users_dat_birth', sa.DateTime(), nullable=False),
    sa.Column('users_ind_active', sa.Boolean(), nullable=False),
    sa.Column('users_dat_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('users_dat_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('users_id')
    )
    op.create_index(op.f('ix_users_users_cod_cpf'), 'users', ['users_cod_cpf'], unique=True)
    op.create_index(op.f('ix_users_users_email'), 'users', ['users_email'], unique=True)
    op.create_index(op.f('ix_users_users_nam'), 'users', ['users_nam'], unique=False)
    op.create_table('adres',
    sa.Column('users_id', sa.UUID(), nullable=False),
    sa.Column('adres_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('adres_cod_country', sa.String(length=2), nullable=False),
    sa.Column('adres_cod_state', sa.String(length=2), nullable=False),
    sa.Column('adres_nam_city', sa.String(length=50), nullable=False),
    sa.Column('adres_nam_neighborhood', sa.String(length=50), nullable=False),
    sa.Column('adres_nam_road', sa.String(length=50), nullable=True),
    sa.Column('adres_cod_number', sa.String(length=10), nullable=True),
    sa.Column('adres_ind_public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('users_id', 'adres_id')
    )
    op.create_index(op.f('ix_adres_adres_cod_country'), 'adres', ['adres_cod_country'], unique=True)
    op.create_index(op.f('ix_adres_adres_cod_state'), 'adres', ['adres_cod_state'], unique=True)
    op.create_index(op.f('ix_adres_adres_nam_city'), 'adres', ['adres_nam_city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adres_adres_nam_city'), table_name='adres')
    op.drop_index(op.f('ix_adres_adres_cod_state'), table_name='adres')
    op.drop_index(op.f('ix_adres_adres_cod_country'), table_name='adres')
    op.drop_table('adres')
    op.drop_index(op.f('ix_users_users_nam'), table_name='users')
    op.drop_index(op.f('ix_users_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_users_cod_cpf'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
