"""cep

Revision ID: bfc296086024
Revises: 827a8c6b4689
Create Date: 2024-05-30 10:52:37.411176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc296086024'
down_revision: Union[str, None] = '827a8c6b4689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('cep', sa.Integer(), nullable=False))
    op.drop_index('ix_addresses_country', table_name='addresses')
    op.drop_column('addresses', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.create_index('ix_addresses_country', 'addresses', ['country'], unique=False)
    op.drop_column('addresses', 'cep')
    # ### end Alembic commands ###
